# Generated by Django 3.1.3 on 2021-04-21 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_auto_20210421_0621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='entry_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
